import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Bottom/Footer";
import Navbar from "@/components/Header/Navbar";
import PromoCards from "@/components/Bottom/PromoCards";
import { getServerSession } from "next-auth";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col antialiased">
        <Providers session={session}>
          <Navbar />
          <main className="flex-1">{children}</main>
          <PromoCards />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
